# Generated by Django 4.1.2 on 2022-11-08 02:29

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Название организации', max_length=255)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='org', verbose_name='Логотип')),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Настройка Организации',
            },
        ),
    ]
