# Generated by Django 4.1.2 on 2022-12-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': '2. Города'},
        ),
    ]
