# Generated by Django 4.1.2 on 2022-11-08 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_organizationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Фраза')),
                ('visible', models.BooleanField(default=False, verbose_name='Отображать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фраза дня',
                'verbose_name_plural': 'Фразы дня',
            },
        ),
        migrations.AlterField(
            model_name='organizationconfig',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizationconfig',
            name='org_name',
            field=models.CharField(default='Название организации', max_length=255, verbose_name='Название организации'),
        ),
        migrations.CreateModel(
            name='PhraseDayLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='organization.phraseday')),
            ],
        ),
    ]
