# Generated by Django 4.1.2 on 2022-11-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_phraseday_alter_organizationconfig_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Департамент', 'verbose_name_plural': '3. Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': '2. Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='organizationconfig',
            options={'verbose_name': '1. Настройка'},
        ),
        migrations.AlterModelOptions(
            name='phraseday',
            options={'verbose_name': 'Фраза дня', 'verbose_name_plural': '4. Фразы дня'},
        ),
        migrations.CreateModel(
            name='PhraseForHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='organization.organizationconfig')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.phraseday')),
            ],
        ),
    ]
