# Generated by Django 4.1.2 on 2022-12-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='ideas_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта на которую отправлять новые идеи'),
        ),
    ]
