# Generated by Django 4.1.2 on 2022-11-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_department_options_alter_filial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phraseforhomepage',
            options={'verbose_name': 'Фраза дня', 'verbose_name_plural': 'Фразы которые отображать на Главной Странице'},
        ),
        migrations.RemoveField(
            model_name='phraseday',
            name='visible',
        ),
        migrations.AlterField(
            model_name='phraseforhomepage',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.phraseday', verbose_name='Фраза'),
        ),
    ]
