# Generated by Django 4.1.2 on 2022-11-08 06:10

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_phraseforhomepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='default_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Изображение которое используется если у объекта оно не установлено', null=True, upload_to='org', verbose_name='Заглушка'),
        ),
        migrations.AlterField(
            model_name='organizationconfig',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='phraseforhomepage',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.phraseday', verbose_name='Фраза дня'),
        ),
    ]
