# Generated by Django 4.1.2 on 2022-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organizationconfig_default_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='director_feedback_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта на которую отправлять обращения директору'),
        ),
        migrations.AddField(
            model_name='organizationconfig',
            name='feedback_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта на которую отправлять обращения'),
        ),
    ]
