# Generated by Django 4.1.2 on 2022-11-11 03:19

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organizationconfig_director_feedback_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Подробности')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='banners', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_view', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='organization.organizationconfig')),
            ],
        ),
    ]
