# Generated by Django 4.1.2 on 2022-11-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_banner_background_color_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('ALL', 'Изображение + текст'), ('IMAGE', 'Только Изображение'), ('TEXT', 'Только Текст')], default='ALL', max_length=20, verbose_name='Тип баннера'),
        ),
    ]
