# Generated by Django 4.1.2 on 2022-11-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('organization', '0011_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='albums_folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder', verbose_name='Папка для фотоальбомов'),
        ),
    ]
