# Generated by Django 4.1.2 on 2022-11-26 09:45

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('organization', '0013_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='knowledge_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.folder', verbose_name='Папка для базы знаний'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizationconfig',
            name='albums_folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.folder', verbose_name='Папка для фотоальбомов'),
        ),
    ]
