# Generated by Django 4.1.2 on 2022-12-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='IdeaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '4. Страница банка идей',
                'verbose_name_plural': '4. Настройка банка идей',
            },
        ),
        migrations.CreateModel(
            name='ReleasedEmployeeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Контент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Реализованная идея',
                'verbose_name_plural': '5. Реализованные идеи',
            },
        ),
        migrations.CreateModel(
            name='IdeaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=512, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Обращение')),
                ('status', models.CharField(choices=[('CREATED', 'Создано'), ('RESOLVED', 'Обработано')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='от Сотрудника')),
            ],
            options={
                'verbose_name': 'Идея от сотрудника',
                'verbose_name_plural': '3. Банк идей',
            },
        ),
        migrations.CreateModel(
            name='FeedbackForDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=512, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Обращение')),
                ('status', models.CharField(choices=[('CREATED', 'Создано'), ('RESOLVED', 'Обработано')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='от Сотрудника')),
            ],
            options={
                'verbose_name': 'Вопрос директору',
                'verbose_name_plural': '2. Вопросы Директору',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=512, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Обращение')),
                ('status', models.CharField(choices=[('CREATED', 'Создано'), ('RESOLVED', 'Обработано')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('type', models.CharField(choices=[('QUESTION', 'Вопрос'), ('IDEA', 'Идея')], default='QUESTION', max_length=20, verbose_name='Тип обращения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='от Сотрудника')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': '1. Обращения',
            },
        ),
    ]
