# Generated by Django 4.1.2 on 2022-11-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('QUESTION', 'Вопрос'), ('FEEDBACK', 'Обращение'), ('IDEA', 'Идея')], default='QUESTION', max_length=20, verbose_name='Тип обращения'),
        ),
    ]
