# Generated by Django 4.1.2 on 2022-11-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedbackcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('QUESTION', 'Вопрос'), ('REVIEW', 'Отзыв'), ('IDEA', 'Идея')], default='QUESTION', max_length=20, verbose_name='Тип обращения'),
        ),
    ]
