# Generated by Django 4.1.2 on 2022-12-22 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_alter_releasedemployeeidea_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedemployeeidea',
            name='employee',
        ),
        migrations.AddField(
            model_name='releasedemployeeidea',
            name='employee',
            field=models.ManyToManyField(null=True, related_name='released_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
