# Generated by Django 4.1.2 on 2022-11-19 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0003_alter_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('QUESTION', 'Вопрос'), ('IDEA', 'Идея')], default='QUESTION', max_length=20, verbose_name='Тип обращения'),
        ),
        migrations.CreateModel(
            name='IdeaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=512, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Обращение')),
                ('status', models.CharField(choices=[('CREATED', 'Создано'), ('RESOLVED', 'Обработано')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='от Сотрудника')),
            ],
            options={
                'verbose_name': 'Идея от сотрудника',
                'verbose_name_plural': 'Банк идей',
            },
        ),
    ]
