# Generated by Django 4.1.2 on 2022-12-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Отправлено'), ('INPROGRESS', 'На рассмотрении'), ('RESOLVED', 'Рассмотрено')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('QUESTION', 'Вопрос')], default='QUESTION', max_length=20, verbose_name='Тип обращения'),
        ),
        migrations.AlterField(
            model_name='feedbackfordirector',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Отправлено'), ('INPROGRESS', 'На рассмотрении'), ('RESOLVED', 'Рассмотрено')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ideafeedback',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Отправлено'), ('INPROGRESS', 'На рассмотрении'), ('RESOLVED', 'Рассмотрено')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
