# Generated by Django 4.1.2 on 2022-11-19 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0004_alter_feedback_type_ideafeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'Страница банка идей',
                'verbose_name_plural': 'Настройка банка идей',
            },
        ),
        migrations.CreateModel(
            name='ReleasedEmployeeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='awards', verbose_name='Изображение')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Реализованная идея',
                'verbose_name_plural': 'Реализованные идеи',
            },
        ),
    ]
