# Generated by Django 4.1.2 on 2022-11-20 13:22

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_ideapage_releasedemployeeidea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideafeedback',
            options={'verbose_name': 'Идея от сотрудника', 'verbose_name_plural': '3. Банк идей'},
        ),
        migrations.AlterModelOptions(
            name='ideapage',
            options={'verbose_name': '4. Страница банка идей', 'verbose_name_plural': '4. Настройка банка идей'},
        ),
        migrations.AlterField(
            model_name='ideapage',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
