# Generated by Django 4.1.2 on 2022-11-27 03:52

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_ideafeedback_options_alter_ideapage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedemployeeidea',
            name='image',
        ),
        migrations.AlterField(
            model_name='releasedemployeeidea',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
