# Generated by Django 4.1.2 on 2022-12-10 11:57

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import django_editorjs_fields.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', verbose_name='Название для ulr')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Контент')),
                ('status', models.CharField(choices=[('DRAFTED', 'Черновик'), ('PUBLISHED', 'Опубликовано')], default='DRAFTED', max_length=20, verbose_name='Статус')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('count_words', models.CharField(default=0, max_length=50, verbose_name='Всего слов')),
                ('read_time', models.CharField(default=0, max_length=50, verbose_name='Время чтения')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='Название для ulr')),
                ('date_published', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата и время после которой публикация станет доступной для чтения', null=True, verbose_name='Дата публикации')),
                ('home_view', models.BooleanField(default=True, verbose_name='Отображать на главной')),
                ('main_image', sorl.thumbnail.fields.ImageField(blank=True, help_text='Изображение в формате jpg, с соотношением сторон 16:9, рекомендуемое разрещение 1400x400', null=True, upload_to='images/posts', verbose_name='Заглавное изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
