# Generated by Django 4.1.2 on 2022-10-29 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=5000)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Код формы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=10000, verbose_name='Описание')),
                ('background_color', models.CharField(default='#d9efed', max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#272124', max_length=20, verbose_name='Цвет текста')),
                ('collect_email', models.BooleanField(default=False, verbose_name='Сбор почты')),
                ('authenticated_responder', models.BooleanField(default=True, verbose_name='Только зарегистрированные пользователи')),
                ('edit_after_submit', models.BooleanField(default=False, verbose_name='Редактирование после отправки')),
                ('confirmation_message', models.CharField(default='Спасибо за участие!', max_length=10000, verbose_name='Сообщение после отправки')),
                ('is_quiz', models.BooleanField(default=False, verbose_name='Тест')),
                ('allow_view_score', models.BooleanField(default=True, verbose_name='Показывать результаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=20, verbose_name='Код ответа')),
                ('responder_ip', models.CharField(max_length=30, verbose_name='IP адрес')),
                ('responder_email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL, verbose_name='Ответивший')),
                ('response', models.ManyToManyField(related_name='response', to='polls.answer', verbose_name='Ответы')),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to='polls.form', verbose_name='Форма')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000, verbose_name='Вопрос')),
                ('question_type', models.CharField(max_length=20, verbose_name='Тип вопроса')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('answer_key', models.CharField(blank=True, max_length=5000, verbose_name='Ключ ответа')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Баллы')),
                ('feedback', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Обратная связь')),
                ('choices', models.ManyToManyField(related_name='choices', to='polls.choices', verbose_name='Варианты ответа')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='polls.questions', verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to', to='polls.questions', verbose_name='Вопрос'),
        ),
    ]
