# Generated by Django 4.1.2 on 2022-11-10 05:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.form_questions',),
        ),
        migrations.CreateModel(
            name='QuestionsProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.questions_choices',),
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': '3. Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма опроса', 'verbose_name_plural': '1. Формы'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': '2. Вопросы'},
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice',
            field=models.CharField(max_length=5000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='form',
            name='background_color',
            field=colorfield.fields.ColorField(default='#f9f8f9', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Спасибо за участие!', max_length=10000, verbose_name='Сообщение после прохождения'),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='form',
            name='is_quiz',
            field=models.BooleanField(default=False, verbose_name='Квиз'),
        ),
        migrations.AlterField(
            model_name='form',
            name='text_color',
            field=colorfield.fields.ColorField(default='#222', image_field=None, max_length=18, samples=None, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('multiple choice', 'Один из списка'), ('checkbox', 'Несколько из списка'), ('short', 'Крактий ответ'), ('paragraph', 'Развернутый ответ')], default='multiple choice', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
