# Generated by Django 4.1.2 on 2022-12-17 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='internal_phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Внутренний телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Email должен быть уникальным, так как будет служить для авторизации сотрудников на портале', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=150, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.position', verbose_name='Должность'),
        ),
    ]
