# Generated by Django 4.1.2 on 2022-11-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_department_description'),
        ('employees', '0003_employeelikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department', verbose_name='Департамент'),
        ),
    ]
