# Generated by Django 4.1.2 on 2022-12-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_city_options'),
        ('employees', '0005_employeeadditionalposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeadditionalposition',
            options={'verbose_name': 'Дополнительная должность', 'verbose_name_plural': 'Дополнительные должности'},
        ),
        migrations.AlterField(
            model_name='employeeadditionalposition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employeeadditionalposition',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.position', verbose_name='Должность'),
        ),
    ]
