# Generated by Django 4.1.2 on 2022-12-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeeadditionalposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
