# Generated by Django 4.1.2 on 2022-12-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tree_root',
            field=models.BooleanField(default=False, verbose_name='Главный в иерархии'),
        ),
    ]
