# Generated by Django 4.1.2 on 2022-12-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_tree_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tree_root',
            field=models.BooleanField(default=False, verbose_name='Первый в иерархии'),
        ),
    ]
